.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pvc-fn-gen5 1  "pvc-fn-gen5 " 
.SH NAME
pvc\-fn\-gen5 \- gen5: sum of arbitrary `(harmonic, amplitude, phase)` partials (`legacy/cmusic_gen/gen/gen5.c`)
.SH SYNOPSIS
\fBpvc\-fn\-gen5\fR <\fB\-L\fR|\fB\-\-length\fR> [\fB\-\-closed\fR] <\fB\-\-partial\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIOUTPUT\fR> 
.SH DESCRIPTION
gen5: sum of arbitrary `(harmonic, amplitude, phase)` partials (`legacy/cmusic_gen/gen/gen5.c`)
.SH OPTIONS
.TP
\fB\-L\fR, \fB\-\-length\fR \fI<LENGTH>\fR

.TP
\fB\-\-closed\fR

.TP
\fB\-\-partial\fR \fI<PARTIALS>\fR
A partial as `harmonic,amplitude,phase`; repeat for each one
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIOUTPUT\fR>

