.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pvc-info 1  "pvc-info " 
.SH NAME
pvc\-info \- Show details of an audio file or a .pva file
.SH SYNOPSIS
\fBpvc\-info\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> 
.SH DESCRIPTION
Show details of an audio file or a .pva file
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>
Path to an audio file (wav/aiff/flac/...) or a `.pva` file
