.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pvc-pitch 1  "pvc-pitch " 
.SH NAME
pvc\-pitch \- Pitch transposition only \- `pvc pv \-\-pitch <semitones>` with everything else at its default
.SH SYNOPSIS
\fBpvc\-pitch\fR <\fB\-\-semitones\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIINPUT\fR> <\fIOUTPUT\fR> 
.SH DESCRIPTION
Pitch transposition only \- `pvc pv \-\-pitch <semitones>` with everything else at its default
.SH OPTIONS
.TP
\fB\-\-semitones\fR \fI<SEMITONES>\fR
Pitch shift in semitones (positive = up, negative = down)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIINPUT\fR>

.TP
<\fIOUTPUT\fR>

