.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pvc-preset-list 1  "pvc-preset-list " 
.SH NAME
pvc\-preset\-list \- List example presets bundled with `pvc`
.SH SYNOPSIS
\fBpvc\-preset\-list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List example presets bundled with `pvc`
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
