.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pvc-stretch 1  "pvc-stretch " 
.SH NAME
pvc\-stretch \- Time\-stretch only \- `pvc pv \-\-stretch <factor>` with everything else at its default
.SH SYNOPSIS
\fBpvc\-stretch\fR <\fB\-\-factor\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIINPUT\fR> <\fIOUTPUT\fR> 
.SH DESCRIPTION
Time\-stretch only \- `pvc pv \-\-stretch <factor>` with everything else at its default
.SH OPTIONS
.TP
\fB\-\-factor\fR \fI<FACTOR>\fR
Time\-stretch factor (`1.0` = unchanged, `2.0` = twice as long)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIINPUT\fR>

.TP
<\fIOUTPUT\fR>

