.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pvc-fn-gen3 1  "pvc-fn-gen3 " 
.SH NAME
pvc\-fn\-gen3 \- gen3: piecewise\-linear envelope at evenly spaced breakpoints, given only their values (`legacy/cmusic_gen/gen/gen3.c`)
.SH SYNOPSIS
\fBpvc\-fn\-gen3\fR <\fB\-L\fR|\fB\-\-length\fR> [\fB\-\-open\fR] <\fB\-\-value\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIOUTPUT\fR> 
.SH DESCRIPTION
gen3: piecewise\-linear envelope at evenly spaced breakpoints, given only their values (`legacy/cmusic_gen/gen/gen3.c`)
.SH OPTIONS
.TP
\fB\-L\fR, \fB\-\-length\fR \fI<LENGTH>\fR

.TP
\fB\-\-open\fR

.TP
\fB\-\-value\fR \fI<VALUES>\fR
A breakpoint value; repeat for each point (need at least two)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIOUTPUT\fR>

