.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pvc-preset-init 1  "pvc-preset-init " 
.SH NAME
pvc\-preset\-init \- Emit an annotated default preset for a tool
.SH SYNOPSIS
\fBpvc\-preset\-init\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITOOL\fR> 
.SH DESCRIPTION
Emit an annotated default preset for a tool
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITOOL\fR>
Tool name, e.g. `pv`
