//! Golden harness integration test for `pvc pv` (Task 3.2's "first real
//! parity milestone"): runs `pvc pv` with flags equivalent to each
//! `tests/golden/cases/plainpv/*.toml` case's `legacy_steps`, then
//! compares against the recorded C-oracle output using the existing
//! `tests/golden/compare.py` (kept in Python rather than reimplemented -
//! it's shared infra also used for C-vs-C sanity checks).
//!
//! Requires `tests/golden/expected/plainpv/` to already be populated via
//! `bash tests/golden/run_legacy.sh` (not git-tracked - regenerated by
//! CI's `golden` job, or locally on demand) and a `python3` on `PATH`.
//! Each case skips itself with a clear message rather than failing
//! confusingly when either prerequisite is missing, so a bare `cargo
//! test` in a dev environment without the legacy toolkit built doesn't
//! look like a Rust regression.

use std::path::{Path, PathBuf};
use std::process::Command;

fn repo_root() -> PathBuf {
    // This crate lives at <repo>/rust/crates/pvc-cli.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .canonicalize()
        .expect("repo root should exist")
}

fn python3_available() -> bool {
    Command::new("python3")
        .arg("--version")
        .output()
        .is_ok_and(|o| o.status.success())
}

/// Runs `pvc <pvc_args> <input> <out_path>`, then `compare.py
/// plainpv/<case> <out_path>`. Skips (prints and returns) if the
/// recorded expected output or `python3` aren't available.
fn run_case(case: &str, pvc_args: &[&str], input_fixture: &str, output_ext: &str) {
    let root = repo_root();
    let expected_dir = root.join("tests/golden/expected/plainpv").join(case);
    if !expected_dir.is_dir() {
        eprintln!(
            "SKIP golden_plainpv::{case}: {} not found - run `bash tests/golden/run_legacy.sh` first",
            expected_dir.display()
        );
        return;
    }
    if !python3_available() {
        eprintln!("SKIP golden_plainpv::{case}: python3 not found on PATH");
        return;
    }

    let input = root.join("tests/golden/fixtures").join(input_fixture);
    let out_path = std::env::temp_dir().join(format!("pvc_golden_plainpv_{case}.{output_ext}"));

    let status = Command::new(env!("CARGO_BIN_EXE_pvc"))
        .args(pvc_args)
        .arg(&input)
        .arg(&out_path)
        .status()
        .expect("failed to run pvc");
    assert!(
        status.success(),
        "`pvc {pvc_args:?}` failed for case {case}"
    );

    let compare = Command::new("python3")
        .arg(root.join("tests/golden/compare.py"))
        .arg(format!("plainpv/{case}"))
        .arg(&out_path)
        .output()
        .expect("failed to run compare.py");
    assert!(
        compare.status.success(),
        "compare.py failed for plainpv/{case}:\n{}{}",
        String::from_utf8_lossy(&compare.stdout),
        String::from_utf8_lossy(&compare.stderr)
    );
}

#[test]
fn stretch() {
    run_case(
        "stretch",
        &["pv", "--fft", "1024", "--stretch", "2.0"],
        "sine440_2s_44k.wav",
        "wav",
    );
}

#[test]
fn pitch_transpose_oscbank() {
    run_case(
        "pitch_transpose_oscbank",
        &["pv", "--fft", "2048", "--pitch", "7", "--threshold", "-60"],
        "sine440_2s_44k.wav",
        "wav",
    );
}

#[test]
fn pitch_control_function() {
    let root = repo_root();
    let ramp = root.join("tests/golden/fixtures/ramp.txt");
    let pitch_arg = format!("@{}", ramp.display());
    run_case(
        "pitch_control_function",
        &["pv", "--fft", "1024", "--pitch", &pitch_arg],
        "sine440_2s_44k.wav",
        "wav",
    );
}

#[test]
fn warp_and_shelf_eq() {
    run_case(
        "warp_and_shelf_eq",
        &[
            "pv",
            "--fft",
            "1024",
            "--warp",
            "0.5",
            "--shelf-low-gain",
            "-6",
            "--shelf-high-gain",
            "6",
        ],
        "sine440_2s_44k.wav",
        "wav",
    );
}

#[test]
fn stereo_input() {
    run_case(
        "stereo_input",
        &["pv", "--fft", "1024", "--stretch", "1.5"],
        "stereo_two_tones_44k.wav",
        "wav",
    );
}
