[workspace]
resolver = "2"
members = ["crates/pvc-core", "crates/pvc-io", "crates/pvc-cli"]

[workspace.package]
version = "0.1.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/mjladd/pvcplus"
rust-version = "1.87"

[profile.release]
lto = true
codegen-units = 1

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
